import java.io.IOException;
import java.util.Date;

public class LTSpiceBatchMode implements Logging{
	
	private String command;
	
	public LTSpiceBatchMode() {
	}
	
	
	@Override
	public void log(){
		System.out.println("sim1.log, Sim1.net and Sim1.raw file generated");		
	}

	@Override
	public void printLog() {
		System.out.println("The log is generated by LTSpice");
	}

	public static void main(String[] args) throws IOException {
		try {
			System.out.println("Opening LTSPice. Time: " + new Date());
			Runtime runTime = Runtime.getRuntime();
			//Process process = runTime.exec("scad3");//Must be added to the path variable in windows
			
			String commandToSend = "scad3.exe -b Sim2.asc -Run -ascii";
			//String commandToSend = "scad3.exe -b ./data/Sim2/Sim2.asc -Run -ascii";			
			Process process = runTime.exec(commandToSend);//Must be added to the path variable in windows
			try {
				process.waitFor();
				//Thread.sleep(15000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
			System.out.println("Closing LTSpice. Time: " + new Date());
			process.destroy();
		} catch (IOException e) {
			e.printStackTrace();
		}

	}
}